controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

legacy_doc:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: /dimensions
        permanent: false
